networks:
  default:
    external: true
    name: build-network

volumes:
  jenkins_home:
  gitea_persistence:
  sshkey:
  certs:

services:
  postgresql:
    image: postgres:16-alpine
#    ports:
#      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
  nginx:
    image:
      nginx
    container_name: reverseProxy
  jenkins:
    image:
      jenkins/jenkins:lts-jdk17
#    ports:
#      - "8080:8080"
    volumes:
      - "jenkins_home:/var/jenkins_home"
  gerrit:
    image:
      docker.io/gerritcodereview/gerrit
  gitea:
    depends_on:
      - postgresql
    image: bitnami/gitea
    volumes:
      - gitea_persistence:/bitnami/gitea
    environment:
      - ALLOW_EMPTY_PASSWORD=false
      - GITEA_DOMAIN=tahoma.lan
      - GITEA_DATABASE_HOST=127.0.0.1
      - GITEA_DATABASE_PORT_NUMBER=5432
      - GITEA_DATABASE_PASSWORD=password
  jenkins-ssh-agent:
    image: jenkins/ssh-agent
#  zuul-scheduler:
#    image: quay.io/zuul-ci/zuul-scheduler
#    volumes:
#      - "sshkey:/var/ssh:z"
#      - "certs:/ver/certs:z"
#    environment:
#      - http_proxy
#      - https_proxy
#  zuul-web:
#    image: quay.io/zuul-ci/zuul-web
##  zuul-executor:
##    image: quay.io/zuul-ci/zuul-executor
##    volumes:
##      - "sshkey:/var/ssh:z"
#  zuul-launcher:
#    image: quay.io/zuul-ci/nodepool-launcher
#    volumes:
#      - "certs:/var/certs:z"





