CXXFLAGS:=-std=c++17 -pthread
CXXFLAGS+=-fsanitize=undefined 
CXXFLAGS+=-Werror=all -Werror=extra

all: chainablePromise sendFile isatty broken

broken: UDPSocketServer quicServer geoParticleFilter antColonyOptimization
