---
name: C/C++ CI
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory
    steps:
    - uses: actions/checkout@v3
    - uses: lukka/get-cmake@latest
    - name: cmake
      run: cmake -B cmake-build -S . -GNinja && cmake --build cmake-build
    - name: meson inspection
      run: which meson
    - name: install meson
      run: python3 -m pip install meson && which meson
  sonarcloud:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: Install sonar-scanner and build-wrapper
      uses: SonarSource/sonarcloud-github-c-cpp@v1
    - name: Run build-wrapper
      run: |
        mkdir build
        cmake -S . -B build
        build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} cmake --build build
    - name: Run sonar-scanner
      run: |
        sonar-scanner --define sonar.cfamily.build-wrapper-output="${{ env.BUILD_WRAPPER_OUT_DIR }}"
