---
name: C/C++ CI
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: lukka/get-cmake@latest
    - name: cmake
      run: cmake -B cmake-build -S . -GNinja && cmake --build cmake-build
    - name: install meson
      run: python3 -m pip install https://github.com/mesonbuild/meson/releases/download/1.0.0/meson-1.0.0.tar.gz && which meson
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Run build-wrapper
      run: |
        cmake -S . -B build
        which build-wrapper-linux-x86_64 || echo "failed while looking for wrapper command"
        which ninja || echo "ninja not found"
        build-wrapper-linux-x86-64 --out-dir cmake-build-sonarcube-wrap cmake --build build || echo "failed to run wrapper command"
    - name: run tox
      run: python3 -m pip install tox && tox -e py